class CreateStandings < ActiveRecord::Migration
  def change
    create_table :standings do |t|
      t.string :team_name1
      t.string :pld1
      t.string :w1
      t.string :d1
      t.string :l1
      t.string :gf1
      t.string :ga1
      t.string :gd1
      t.string :pts1
      t.string :qualification1
      t.string :team_name2
      t.string :pld2
      t.string :w2
      t.string :d2
      t.string :l2
      t.string :gf2
      t.string :ga2
      t.string :gd2
      t.string :pts2
      t.string :qualification2
      t.string :team_name3
      t.string :pld3
      t.string :w3
      t.string :d3
      t.string :l3
      t.string :gf3
      t.string :ga3
      t.string :gd3
      t.string :pts3
      t.string :qualification3
      t.string :team_name4
      t.string :pld4
      t.string :w4
      t.string :d4
      t.string :l4
      t.string :gf4
      t.string :ga4
      t.string :gd4
      t.string :pts4
      t.string :qualification4
      t.string :team_name5
      t.string :pld5
      t.string :w5
      t.string :d5
      t.string :l5
      t.string :gf5
      t.string :ga5
      t.string :gd5
      t.string :pts5
      t.string :qualification5
      t.string :team_name6
      t.string :pld6
      t.string :w6
      t.string :d6
      t.string :l6
      t.string :gf6
      t.string :ga6
      t.string :gd6
      t.string :pts6
      t.string :qualification6
      t.string :team_name7
      t.string :pld7
      t.string :w7
      t.string :d7
      t.string :l7
      t.string :gf7
      t.string :ga7
      t.string :gd7
      t.string :pts7
      t.string :qualification7
      t.string :team_name8
      t.string :pld8
      t.string :w8
      t.string :d8
      t.string :l8
      t.string :gf8
      t.string :ga8
      t.string :gd8
      t.string :pts8
      t.string :qualification8
      t.string :team_name9
      t.string :pld9
      t.string :w9
      t.string :d9
      t.string :l9
      t.string :gf9
      t.string :ga9
      t.string :gd9
      t.string :pts9
      t.string :qualification9
      t.string :team_name10
      t.string :pld10
      t.string :w10
      t.string :d10
      t.string :l10
      t.string :gf10
      t.string :ga10
      t.string :gd10
      t.string :pts10
      t.string :qualification10
      t.string :team_name11
      t.string :pld11
      t.string :w11
      t.string :d11
      t.string :l11
      t.string :gf11
      t.string :ga11
      t.string :gd11
      t.string :pts11
      t.string :qualification11
      t.string :team_name12
      t.string :pld12
      t.string :w12
      t.string :d12
      t.string :l12
      t.string :gf12
      t.string :ga12
      t.string :gd12
      t.string :pts12
      t.string :qualification12
      t.timestamps
    end
  end
end
